name: Deploy

on: [push]

env:
  TZ: 'Asia/Taipei'

jobs:
  build:
    runs-on: ubuntu-latest

    name: Deploy Hexo Blog
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true # Checkout private submodules(themes or something else).

    - name: Timezone set Asia/Taipei
      run: sudo timedatectl set-timezone 'Asia/Taipei'

    - name: Yarn Install
      uses: borales/actions-yarn@v4
      with:
        cmd: install

    - name: Hexo Build
      run: yarn -m hexo build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DEPLOY_KEY }}
        publish_dir: ../public


    - name: Get the output
      run: |
        echo "${{ steps.deploy.outputs.notify }}"

